services:
  postgres:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d redline"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  nats:
    image: nats:2.14-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    env_file:
      - .env
    command: ["-c", "/etc/nats/nats.conf"]
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - nats_data:/data
      - ./config/nats/nats.conf:/etc/nats/nats.conf:ro
    networks:
      - app-network

  grid-worker:
    image: redline/grid-worker
    env_file:
      - ./services/grid-worker/.env.docker
    networks:
      - app-network
    depends_on:
      nats:
        condition: service_healthy

  race-control:
    image: redline/race-control
    env_file:
      - ./services/race-control/.env.docker
    networks:
      - app-network
    depends_on:
      nats:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  nats_data:

networks:
  app-network:
    driver: bridge