# https://taskfile.dev

version: '3'

tasks:
  paddock:
    dir: apps/paddock
    cmds:
      - pnpm run dev

  up:
    cmds:
      - docker compose up -d

  down:
    cmds:
      - docker compose down


  db:
    cmds:
      - docker compose up postgres -d

  nats:
    cmds:
      - docker compose up nats -d

  psql:
    cmds:
      - docker compose exec postgres psql -U postgres -d redline

  db-generate:
    dir: apps/paddock
    cmds:
      - pnpm dlx auth@latest generate --output ./lib/db/schema/auth-schema.ts
      - pnpm drizzle-kit generate

  db-migrate:
    dir: apps/paddock
    cmds:
      - pnpm drizzle-kit migrate

  grid-worker:
    dir: services/grid-worker
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    cmds:
      - go run .

  race-control:
    dir: services/race-control
    cmds:
      - go run .

  pb-gen:
    cmds:
      - buf build
      - buf generate