# https://taskfile.dev

version: "3"

tasks:
  up:
    cmds:
      - docker compose up -d

  up-build:
    cmds:
      - task: docker-grid-worker
      - task: docker-grid-worker
      - docker compose up -d

  down:
    cmds:
      - docker compose down

  postgres:
    cmds:
      - docker compose up postgres -d

  nats:
    cmds:
      - docker compose up nats -d

  timescale:
    cmds:
      - docker compose up timescale -d

  infra:
    cmds:
     - docker compose up postgres nats timescale -d

  psql:
    cmds:
      - docker compose exec postgres psql -U postgres -d redline

  docker-grid-worker:
    dir: services
    cmds:
      - docker build -f grid-worker/Dockerfile -t redline/grid-worker .

  docker-race-control:
    dir: services
    cmds:
      - docker build -f race-control/Dockerfile -t redline/race-control .

  paddock:
    dir: apps/paddock
    cmds:
      - pnpm run dev

  db-generate:
    dir: apps/paddock
    cmds:
      - pnpm dlx auth@latest generate --output ./lib/db/schema/auth-schema.ts
      - pnpm drizzle-kit generate

  db-migrate:
    dir: apps/paddock
    cmds:
      - pnpm drizzle-kit migrate

  grid-worker:
    dir: services/grid-worker
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    cmds:
      - go run .

  race-control:
    dir: services/race-control
    cmds:
      - go run .

  pit-wall:
    dir: services/pit-wall
    cmds:
      - uv run main.py

  pb-gen:
    cmds:
      - buf build
      - buf generate
