// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: monitors/updates.proto

package monitors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_UPSERT      EventType = 1
	EventType_EVENT_TYPE_DELETE      EventType = 2
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_UPSERT",
		2: "EVENT_TYPE_DELETE",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_UPSERT":      1,
		"EVENT_TYPE_DELETE":      2,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_monitors_updates_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_monitors_updates_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type MonitorEvent struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventType   EventType              `protobuf:"varint,1,opt,name=event_type,json=eventType,enum=monitors.EventType"`
	xxx_hidden_MonitorId   *string                `protobuf:"bytes,2,opt,name=monitor_id,json=monitorId"`
	xxx_hidden_Version     int32                  `protobuf:"varint,3,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MonitorEvent) Reset() {
	*x = MonitorEvent{}
	mi := &file_monitors_updates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorEvent) ProtoMessage() {}

func (x *MonitorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_monitors_updates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MonitorEvent) GetEventType() EventType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_EventType
		}
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *MonitorEvent) GetMonitorId() string {
	if x != nil {
		if x.xxx_hidden_MonitorId != nil {
			return *x.xxx_hidden_MonitorId
		}
		return ""
	}
	return ""
}

func (x *MonitorEvent) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *MonitorEvent) SetEventType(v EventType) {
	x.xxx_hidden_EventType = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *MonitorEvent) SetMonitorId(v string) {
	x.xxx_hidden_MonitorId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *MonitorEvent) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *MonitorEvent) HasEventType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MonitorEvent) HasMonitorId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MonitorEvent) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *MonitorEvent) ClearEventType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_EventType = EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *MonitorEvent) ClearMonitorId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MonitorId = nil
}

func (x *MonitorEvent) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Version = 0
}

type MonitorEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EventType *EventType
	MonitorId *string
	Version   *int32
}

func (b0 MonitorEvent_builder) Build() *MonitorEvent {
	m0 := &MonitorEvent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.EventType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_EventType = *b.EventType
	}
	if b.MonitorId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_MonitorId = b.MonitorId
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

var File_monitors_updates_proto protoreflect.FileDescriptor

const file_monitors_updates_proto_rawDesc = "" +
	"\n" +
	"\x16monitors/updates.proto\x12\bmonitors\"{\n" +
	"\fMonitorEvent\x122\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x13.monitors.EventTypeR\teventType\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x02 \x01(\tR\tmonitorId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion*U\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EVENT_TYPE_UPSERT\x10\x01\x12\x15\n" +
	"\x11EVENT_TYPE_DELETE\x10\x02B=Z;github.com/shravanasati/redline/services/shared/pb/monitorsb\beditionsp\xe9\a"

var file_monitors_updates_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_monitors_updates_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_monitors_updates_proto_goTypes = []any{
	(EventType)(0),       // 0: monitors.EventType
	(*MonitorEvent)(nil), // 1: monitors.MonitorEvent
}
var file_monitors_updates_proto_depIdxs = []int32{
	0, // 0: monitors.MonitorEvent.event_type:type_name -> monitors.EventType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_monitors_updates_proto_init() }
func file_monitors_updates_proto_init() {
	if File_monitors_updates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitors_updates_proto_rawDesc), len(file_monitors_updates_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_monitors_updates_proto_goTypes,
		DependencyIndexes: file_monitors_updates_proto_depIdxs,
		EnumInfos:         file_monitors_updates_proto_enumTypes,
		MessageInfos:      file_monitors_updates_proto_msgTypes,
	}.Build()
	File_monitors_updates_proto = out.File
	file_monitors_updates_proto_goTypes = nil
	file_monitors_updates_proto_depIdxs = nil
}
