// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tasks/tasks.proto

package tasks

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	TaskType_TASK_TYPE_ICMP        TaskType = 1
	TaskType_TASK_TYPE_HTTP        TaskType = 2
	TaskType_TASK_TYPE_HTTPS       TaskType = 3
	TaskType_TASK_TYPE_TCP         TaskType = 4
	TaskType_TASK_TYPE_DNS         TaskType = 5
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TASK_TYPE_ICMP",
		2: "TASK_TYPE_HTTP",
		3: "TASK_TYPE_HTTPS",
		4: "TASK_TYPE_TCP",
		5: "TASK_TYPE_DNS",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED": 0,
		"TASK_TYPE_ICMP":        1,
		"TASK_TYPE_HTTP":        2,
		"TASK_TYPE_HTTPS":       3,
		"TASK_TYPE_TCP":         4,
		"TASK_TYPE_DNS":         5,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_tasks_tasks_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_tasks_tasks_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type HTTPMethod int32

const (
	HTTPMethod_HTTP_METHOD_UNSPECIFIED HTTPMethod = 0
	HTTPMethod_HTTP_METHOD_GET         HTTPMethod = 1
	HTTPMethod_HTTP_METHOD_POST        HTTPMethod = 2
	HTTPMethod_HTTP_METHOD_HEAD        HTTPMethod = 3
)

// Enum value maps for HTTPMethod.
var (
	HTTPMethod_name = map[int32]string{
		0: "HTTP_METHOD_UNSPECIFIED",
		1: "HTTP_METHOD_GET",
		2: "HTTP_METHOD_POST",
		3: "HTTP_METHOD_HEAD",
	}
	HTTPMethod_value = map[string]int32{
		"HTTP_METHOD_UNSPECIFIED": 0,
		"HTTP_METHOD_GET":         1,
		"HTTP_METHOD_POST":        2,
		"HTTP_METHOD_HEAD":        3,
	}
)

func (x HTTPMethod) Enum() *HTTPMethod {
	p := new(HTTPMethod)
	*p = x
	return p
}

func (x HTTPMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HTTPMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_tasks_tasks_proto_enumTypes[1].Descriptor()
}

func (HTTPMethod) Type() protoreflect.EnumType {
	return &file_tasks_tasks_proto_enumTypes[1]
}

func (x HTTPMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type MonitorAssertion struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Target      *string                `protobuf:"bytes,1,opt,name=target"`
	xxx_hidden_Operator    *string                `protobuf:"bytes,2,opt,name=operator"`
	xxx_hidden_Value       *string                `protobuf:"bytes,3,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MonitorAssertion) Reset() {
	*x = MonitorAssertion{}
	mi := &file_tasks_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorAssertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorAssertion) ProtoMessage() {}

func (x *MonitorAssertion) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MonitorAssertion) GetTarget() string {
	if x != nil {
		if x.xxx_hidden_Target != nil {
			return *x.xxx_hidden_Target
		}
		return ""
	}
	return ""
}

func (x *MonitorAssertion) GetOperator() string {
	if x != nil {
		if x.xxx_hidden_Operator != nil {
			return *x.xxx_hidden_Operator
		}
		return ""
	}
	return ""
}

func (x *MonitorAssertion) GetValue() string {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
		return ""
	}
	return ""
}

func (x *MonitorAssertion) SetTarget(v string) {
	x.xxx_hidden_Target = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *MonitorAssertion) SetOperator(v string) {
	x.xxx_hidden_Operator = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *MonitorAssertion) SetValue(v string) {
	x.xxx_hidden_Value = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *MonitorAssertion) HasTarget() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MonitorAssertion) HasOperator() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MonitorAssertion) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *MonitorAssertion) ClearTarget() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Target = nil
}

func (x *MonitorAssertion) ClearOperator() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Operator = nil
}

func (x *MonitorAssertion) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Value = nil
}

type MonitorAssertion_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Target   *string
	Operator *string
	Value    *string
}

func (b0 MonitorAssertion_builder) Build() *MonitorAssertion {
	m0 := &MonitorAssertion{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Target != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Target = b.Target
	}
	if b.Operator != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Operator = b.Operator
	}
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Value = b.Value
	}
	return m0
}

type MonitorMetadata struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Headers     map[string]string      `protobuf:"bytes,1,rep,name=headers" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Method      HTTPMethod             `protobuf:"varint,2,opt,name=method,enum=tasks.HTTPMethod"`
	xxx_hidden_Body        *string                `protobuf:"bytes,3,opt,name=body"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MonitorMetadata) Reset() {
	*x = MonitorMetadata{}
	mi := &file_tasks_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorMetadata) ProtoMessage() {}

func (x *MonitorMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MonitorMetadata) GetHeaders() map[string]string {
	if x != nil {
		return x.xxx_hidden_Headers
	}
	return nil
}

func (x *MonitorMetadata) GetMethod() HTTPMethod {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Method
		}
	}
	return HTTPMethod_HTTP_METHOD_UNSPECIFIED
}

func (x *MonitorMetadata) GetBody() string {
	if x != nil {
		if x.xxx_hidden_Body != nil {
			return *x.xxx_hidden_Body
		}
		return ""
	}
	return ""
}

func (x *MonitorMetadata) SetHeaders(v map[string]string) {
	x.xxx_hidden_Headers = v
}

func (x *MonitorMetadata) SetMethod(v HTTPMethod) {
	x.xxx_hidden_Method = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *MonitorMetadata) SetBody(v string) {
	x.xxx_hidden_Body = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *MonitorMetadata) HasMethod() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MonitorMetadata) HasBody() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *MonitorMetadata) ClearMethod() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Method = HTTPMethod_HTTP_METHOD_UNSPECIFIED
}

func (x *MonitorMetadata) ClearBody() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Body = nil
}

type MonitorMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Headers map[string]string
	Method  *HTTPMethod
	Body    *string
}

func (b0 MonitorMetadata_builder) Build() *MonitorMetadata {
	m0 := &MonitorMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Headers = b.Headers
	if b.Method != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Method = *b.Method
	}
	if b.Body != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Body = b.Body
	}
	return m0
}

type MonitorTask struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Type        TaskType               `protobuf:"varint,2,opt,name=type,enum=tasks.TaskType"`
	xxx_hidden_Endpoint    *string                `protobuf:"bytes,3,opt,name=endpoint"`
	xxx_hidden_Timeout     int32                  `protobuf:"varint,4,opt,name=timeout"`
	xxx_hidden_Assertions  *[]*MonitorAssertion   `protobuf:"bytes,5,rep,name=assertions"`
	xxx_hidden_Metadata    *MonitorMetadata       `protobuf:"bytes,6,opt,name=metadata"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MonitorTask) Reset() {
	*x = MonitorTask{}
	mi := &file_tasks_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorTask) ProtoMessage() {}

func (x *MonitorTask) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MonitorTask) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *MonitorTask) GetType() TaskType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *MonitorTask) GetEndpoint() string {
	if x != nil {
		if x.xxx_hidden_Endpoint != nil {
			return *x.xxx_hidden_Endpoint
		}
		return ""
	}
	return ""
}

func (x *MonitorTask) GetTimeout() int32 {
	if x != nil {
		return x.xxx_hidden_Timeout
	}
	return 0
}

func (x *MonitorTask) GetAssertions() []*MonitorAssertion {
	if x != nil {
		if x.xxx_hidden_Assertions != nil {
			return *x.xxx_hidden_Assertions
		}
	}
	return nil
}

func (x *MonitorTask) GetMetadata() *MonitorMetadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *MonitorTask) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *MonitorTask) SetType(v TaskType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *MonitorTask) SetEndpoint(v string) {
	x.xxx_hidden_Endpoint = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *MonitorTask) SetTimeout(v int32) {
	x.xxx_hidden_Timeout = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *MonitorTask) SetAssertions(v []*MonitorAssertion) {
	x.xxx_hidden_Assertions = &v
}

func (x *MonitorTask) SetMetadata(v *MonitorMetadata) {
	x.xxx_hidden_Metadata = v
}

func (x *MonitorTask) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MonitorTask) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MonitorTask) HasEndpoint() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *MonitorTask) HasTimeout() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *MonitorTask) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *MonitorTask) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *MonitorTask) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *MonitorTask) ClearEndpoint() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Endpoint = nil
}

func (x *MonitorTask) ClearTimeout() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Timeout = 0
}

func (x *MonitorTask) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

type MonitorTask_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id         *string
	Type       *TaskType
	Endpoint   *string
	Timeout    *int32
	Assertions []*MonitorAssertion
	Metadata   *MonitorMetadata
}

func (b0 MonitorTask_builder) Build() *MonitorTask {
	m0 := &MonitorTask{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Endpoint != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Endpoint = b.Endpoint
	}
	if b.Timeout != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Timeout = *b.Timeout
	}
	x.xxx_hidden_Assertions = &b.Assertions
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

type MonitorTaskResult struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id             *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Success        bool                   `protobuf:"varint,3,opt,name=success"`
	xxx_hidden_ErrorMessage   *string                `protobuf:"bytes,5,opt,name=error_message,json=errorMessage"`
	xxx_hidden_HttpStatusCode int32                  `protobuf:"varint,6,opt,name=http_status_code,json=httpStatusCode"`
	xxx_hidden_WorkerRegion   *string                `protobuf:"bytes,7,opt,name=worker_region,json=workerRegion"`
	xxx_hidden_Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp"`
	xxx_hidden_Latency        *durationpb.Duration   `protobuf:"bytes,2,opt,name=latency"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MonitorTaskResult) Reset() {
	*x = MonitorTaskResult{}
	mi := &file_tasks_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorTaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorTaskResult) ProtoMessage() {}

func (x *MonitorTaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MonitorTaskResult) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *MonitorTaskResult) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *MonitorTaskResult) GetErrorMessage() string {
	if x != nil {
		if x.xxx_hidden_ErrorMessage != nil {
			return *x.xxx_hidden_ErrorMessage
		}
		return ""
	}
	return ""
}

func (x *MonitorTaskResult) GetHttpStatusCode() int32 {
	if x != nil {
		return x.xxx_hidden_HttpStatusCode
	}
	return 0
}

func (x *MonitorTaskResult) GetWorkerRegion() string {
	if x != nil {
		if x.xxx_hidden_WorkerRegion != nil {
			return *x.xxx_hidden_WorkerRegion
		}
		return ""
	}
	return ""
}

func (x *MonitorTaskResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *MonitorTaskResult) GetLatency() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Latency
	}
	return nil
}

func (x *MonitorTaskResult) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *MonitorTaskResult) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *MonitorTaskResult) SetErrorMessage(v string) {
	x.xxx_hidden_ErrorMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *MonitorTaskResult) SetHttpStatusCode(v int32) {
	x.xxx_hidden_HttpStatusCode = v
}

func (x *MonitorTaskResult) SetWorkerRegion(v string) {
	x.xxx_hidden_WorkerRegion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *MonitorTaskResult) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *MonitorTaskResult) SetLatency(v *durationpb.Duration) {
	x.xxx_hidden_Latency = v
}

func (x *MonitorTaskResult) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MonitorTaskResult) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MonitorTaskResult) HasErrorMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *MonitorTaskResult) HasWorkerRegion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *MonitorTaskResult) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *MonitorTaskResult) HasLatency() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Latency != nil
}

func (x *MonitorTaskResult) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *MonitorTaskResult) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Success = false
}

func (x *MonitorTaskResult) ClearErrorMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ErrorMessage = nil
}

func (x *MonitorTaskResult) ClearWorkerRegion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_WorkerRegion = nil
}

func (x *MonitorTaskResult) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

func (x *MonitorTaskResult) ClearLatency() {
	x.xxx_hidden_Latency = nil
}

type MonitorTaskResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id             *string
	Success        *bool
	ErrorMessage   *string
	HttpStatusCode int32
	WorkerRegion   *string
	Timestamp      *timestamppb.Timestamp
	Latency        *durationpb.Duration
}

func (b0 MonitorTaskResult_builder) Build() *MonitorTaskResult {
	m0 := &MonitorTaskResult{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Id = b.Id
	}
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Success = *b.Success
	}
	if b.ErrorMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_ErrorMessage = b.ErrorMessage
	}
	x.xxx_hidden_HttpStatusCode = b.HttpStatusCode
	if b.WorkerRegion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_WorkerRegion = b.WorkerRegion
	}
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_Latency = b.Latency
	return m0
}

var File_tasks_tasks_proto protoreflect.FileDescriptor

const file_tasks_tasks_proto_rawDesc = "" +
	"\n" +
	"\x11tasks/tasks.proto\x12\x05tasks\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\\\n" +
	"\x10MonitorAssertion\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xcb\x01\n" +
	"\x0fMonitorMetadata\x12=\n" +
	"\aheaders\x18\x01 \x03(\v2#.tasks.MonitorMetadata.HeadersEntryR\aheaders\x12)\n" +
	"\x06method\x18\x02 \x01(\x0e2\x11.tasks.HTTPMethodR\x06method\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe5\x01\n" +
	"\vMonitorTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0f.tasks.TaskTypeR\x04type\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeout\x127\n" +
	"\n" +
	"assertions\x18\x05 \x03(\v2\x17.tasks.MonitorAssertionR\n" +
	"assertions\x122\n" +
	"\bmetadata\x18\x06 \x01(\v2\x16.tasks.MonitorMetadataR\bmetadata\"\xa7\x02\n" +
	"\x11MonitorTaskResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12/\n" +
	"\x10http_status_code\x18\x06 \x01(\x05B\x05\xaa\x01\x02\b\x02R\x0ehttpStatusCode\x12#\n" +
	"\rworker_region\x18\a \x01(\tR\fworkerRegion\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\alatency\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\alatency*\x88\x01\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTASK_TYPE_ICMP\x10\x01\x12\x12\n" +
	"\x0eTASK_TYPE_HTTP\x10\x02\x12\x13\n" +
	"\x0fTASK_TYPE_HTTPS\x10\x03\x12\x11\n" +
	"\rTASK_TYPE_TCP\x10\x04\x12\x11\n" +
	"\rTASK_TYPE_DNS\x10\x05*j\n" +
	"\n" +
	"HTTPMethod\x12\x1b\n" +
	"\x17HTTP_METHOD_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fHTTP_METHOD_GET\x10\x01\x12\x14\n" +
	"\x10HTTP_METHOD_POST\x10\x02\x12\x14\n" +
	"\x10HTTP_METHOD_HEAD\x10\x03B\x85\x01\n" +
	"\tcom.tasksB\n" +
	"TasksProtoP\x01Z8github.com/shravanasati/redline/services/shared/pb/tasks\xa2\x02\x03TXX\xaa\x02\x05Tasks\xca\x02\x05Tasks\xe2\x02\x11Tasks\\GPBMetadata\xea\x02\x05Tasksb\beditionsp\xe9\a"

var file_tasks_tasks_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tasks_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tasks_tasks_proto_goTypes = []any{
	(TaskType)(0),                 // 0: tasks.TaskType
	(HTTPMethod)(0),               // 1: tasks.HTTPMethod
	(*MonitorAssertion)(nil),      // 2: tasks.MonitorAssertion
	(*MonitorMetadata)(nil),       // 3: tasks.MonitorMetadata
	(*MonitorTask)(nil),           // 4: tasks.MonitorTask
	(*MonitorTaskResult)(nil),     // 5: tasks.MonitorTaskResult
	nil,                           // 6: tasks.MonitorMetadata.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 8: google.protobuf.Duration
}
var file_tasks_tasks_proto_depIdxs = []int32{
	6, // 0: tasks.MonitorMetadata.headers:type_name -> tasks.MonitorMetadata.HeadersEntry
	1, // 1: tasks.MonitorMetadata.method:type_name -> tasks.HTTPMethod
	0, // 2: tasks.MonitorTask.type:type_name -> tasks.TaskType
	2, // 3: tasks.MonitorTask.assertions:type_name -> tasks.MonitorAssertion
	3, // 4: tasks.MonitorTask.metadata:type_name -> tasks.MonitorMetadata
	7, // 5: tasks.MonitorTaskResult.timestamp:type_name -> google.protobuf.Timestamp
	8, // 6: tasks.MonitorTaskResult.latency:type_name -> google.protobuf.Duration
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_tasks_tasks_proto_init() }
func file_tasks_tasks_proto_init() {
	if File_tasks_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tasks_tasks_proto_rawDesc), len(file_tasks_tasks_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tasks_tasks_proto_goTypes,
		DependencyIndexes: file_tasks_tasks_proto_depIdxs,
		EnumInfos:         file_tasks_tasks_proto_enumTypes,
		MessageInfos:      file_tasks_tasks_proto_msgTypes,
	}.Build()
	File_tasks_tasks_proto = out.File
	file_tasks_tasks_proto_goTypes = nil
	file_tasks_tasks_proto_depIdxs = nil
}
