// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file monitors/updates.proto (package monitors, edition 2024)
/* eslint-disable */

import type {
  GenEnum,
  GenFile,
  GenMessage,
} from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file monitors/updates.proto.
 */
export const file_monitors_updates: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChZtb25pdG9ycy91cGRhdGVzLnByb3RvEghtb25pdG9ycyJcCgxNb25pdG9yRXZlbnQSJwoKZXZlbnRfdHlwZRgBIAEoDjITLm1vbml0b3JzLkV2ZW50VHlwZRISCgptb25pdG9yX2lkGAIgASgJEg8KB3ZlcnNpb24YAyABKAUqVQoJRXZlbnRUeXBlEhoKFkVWRU5UX1RZUEVfVU5TUEVDSUZJRUQQABIVChFFVkVOVF9UWVBFX1VQU0VSVBABEhUKEUVWRU5UX1RZUEVfREVMRVRFEAJCPVo7Z2l0aHViLmNvbS9zaHJhdmFuYXNhdGkvcmVkbGluZS9zZXJ2aWNlcy9zaGFyZWQvcGIvbW9uaXRvcnNiCGVkaXRpb25zcOkH",
  );

/**
 * @generated from message monitors.MonitorEvent
 */
export type MonitorEvent = Message<"monitors.MonitorEvent"> & {
  /**
   * @generated from field: monitors.EventType event_type = 1;
   */
  eventType: EventType;

  /**
   * @generated from field: string monitor_id = 2;
   */
  monitorId: string;

  /**
   * @generated from field: int32 version = 3;
   */
  version: number;
};

/**
 * Describes the message monitors.MonitorEvent.
 * Use `create(MonitorEventSchema)` to create a new message.
 */
export const MonitorEventSchema: GenMessage<MonitorEvent> =
  /*@__PURE__*/
  messageDesc(file_monitors_updates, 0);

/**
 * @generated from enum monitors.EventType
 */
export enum EventType {
  /**
   * @generated from enum value: EVENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: EVENT_TYPE_UPSERT = 1;
   */
  UPSERT = 1,

  /**
   * @generated from enum value: EVENT_TYPE_DELETE = 2;
   */
  DELETE = 2,
}

/**
 * Describes the enum monitors.EventType.
 */
export const EventTypeSchema: GenEnum<EventType> =
  /*@__PURE__*/
  enumDesc(file_monitors_updates, 0);
